version: "3.9"

services:
    database:
        image: "mcr.microsoft.com/azure-sql-edge"
        ports:
            - 1439:1433
        environment:
            MSSQL_SA_PASSWORD: "todos-123"
            ACCEPT_EULA: "1"
            MSSQL_USER: "SA"
            MSSQL_PID: "Developer"
            
